/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_flexcan.h"
#include "fsl_clock.h"
#include "fsl_pit.h"
#include "fsl_uart.h"
#include "fsl_uart_freertos.h"
#include "fsl_gpio.h"
#include "fsl_port.h"
#include "fsl_debug_console.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define CAN0_PERIPHERAL CAN0
/* Definition of the clock source frequency */
#define CAN0_CLOCK_SOURCE 120000000UL
/* CAN0 interrupt vector ID (number). */
#define CAN0_CAN_ORED_MB_IRQN CAN0_ORed_Message_buffer_IRQn
/* CAN0 interrupt vector priority. */
#define CAN0_CAN_ORED_MB_IRQ_PRIORITY 3
/* CAN0 interrupt handler identifier. */
#define CAN0_CAN_ORED_MB_IRQHANDLER CAN0_ORed_Message_buffer_IRQHandler
/* Definition of peripheral ID */
#define CAN1_PERIPHERAL CAN1
/* Definition of the clock source frequency */
#define CAN1_CLOCK_SOURCE 120000000UL
/* BOARD_InitPeripherals defines for PIT */
/* Definition of peripheral ID. */
#define PIT_PERIPHERAL PIT
/* Definition of clock source frequency. */
#define PIT_CLK_FREQ 24000000UL
/* Definition of ticks count for channel 0 - deprecated. */
#define PIT_0_TICKS 24000U
/* PIT interrupt vector ID (number) - deprecated. */
#define PIT_0_IRQN PIT0_IRQn
/* PIT interrupt vector priority - deprecated. */
#define PIT_0_IRQ_PRIORITY 4
/* PIT interrupt handler identifier - deprecated. */
#define PIT_0_IRQHANDLER PIT0_IRQHandler
/* Definition of channel number for channel 0. */
#define PIT_CHANNEL_0 kPIT_Chnl_0
/* Definition of ticks count for channel 0. */
#define PIT_CHANNEL_0_TICKS 24000U
/* PIT interrupt vector ID (number). */
#define PIT_CHANNEL_0_IRQN PIT0_IRQn
/* PIT interrupt vector priority. */
#define PIT_CHANNEL_0_IRQ_PRIORITY 4
/* PIT interrupt handler identifier. */
#define PIT_CHANNEL_0_IRQHANDLER PIT0_IRQHandler
/* Definition of peripheral ID */
#define UART0_PERIPHERAL UART0
/* Definition of the clock source frequency */
#define UART0_CLOCK_SOURCE CLOCK_GetFreq(UART0_CLK_SRC)
/* Definition of the backround buffer size */
#define UART0_BACKGROUND_BUFFER_SIZE 1
/* UART0 interrupt vector ID (number). */
#define UART0_SERIAL_RX_TX_IRQN UART0_RX_TX_IRQn
/* UART0 interrupt vector ID (number). */
#define UART0_SERIAL_ERROR_IRQN UART0_ERR_IRQn
/* Definition of peripheral ID */
#define UART2_PERIPHERAL UART2
/* Definition of the clock source frequency */
#define UART2_CLOCK_SOURCE CLOCK_GetFreq(UART2_CLK_SRC)
/* Definition of the backround buffer size */
#define UART2_BACKGROUND_BUFFER_SIZE 1
/* UART2 interrupt vector ID (number). */
#define UART2_SERIAL_RX_TX_IRQN UART2_RX_TX_IRQn
/* UART2 interrupt vector ID (number). */
#define UART2_SERIAL_ERROR_IRQN UART2_ERR_IRQn
/* Definition of peripheral ID */
#define UART4_PERIPHERAL UART4
/* Definition of the clock source frequency */
#define UART4_CLOCK_SOURCE CLOCK_GetFreq(UART4_CLK_SRC)
/* Definition of the backround buffer size */
#define UART4_BACKGROUND_BUFFER_SIZE 1
/* UART4 interrupt vector ID (number). */
#define UART4_SERIAL_RX_TX_IRQN UART4_RX_TX_IRQn
/* UART4 interrupt vector ID (number). */
#define UART4_SERIAL_ERROR_IRQN UART4_ERR_IRQn
/* Alias for GPIOB peripheral */
#define GPIOB_GPIO GPIOB
/* Alias for PORTB */
#define GPIOB_PORT PORTB
/* GPIOB interrupt vector ID (number). */
#define GPIOB_IRQN PORTB_IRQn
/* GPIOB interrupt handler identifier. */
#define GPIOB_IRQHANDLER PORTB_IRQHandler
/* Debug console is initialized in the peripheral tool */
#define BOARD_INIT_DEBUG_CONSOLE_PERIPHERAL 
/* Definition of serial peripheral instance */
#define DEBUGCONSOLE_INSTANCE 1U
/* Definition of serial peripheral type */
#define DEBUGCONSOLE_TYPE kSerialPort_Uart
/* Definition of the Baud rate */
#define DEBUGCONSOLE_BAUDRATE 115200UL
/* Definition of the clock source frequency */
#define DEBUGCONSOLE_CLK_FREQ 120000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const flexcan_config_t CAN0_config;
/* Message buffer 0 configuration structure */
extern const flexcan_rx_mb_config_t CAN0_rx_mb_config_0;
/* Message buffer 1 configuration structure */
extern const flexcan_rx_mb_config_t CAN0_rx_mb_config_1;
/* Message buffer 2 configuration structure */
extern const flexcan_rx_mb_config_t CAN0_rx_mb_config_2;
extern flexcan_rx_fifo_config_t CAN0_rx_fifo_config;
extern const flexcan_config_t CAN1_config;
/* Message buffer 0 configuration structure */
extern const flexcan_rx_mb_config_t CAN1_rx_mb_config_0;
extern flexcan_rx_fifo_config_t CAN1_rx_fifo_config;
extern const pit_config_t PIT_config;
extern uart_rtos_handle_t UART0_rtos_handle;
extern uart_handle_t UART0_uart_handle;
extern uart_rtos_config_t UART0_rtos_config;
extern uart_rtos_handle_t UART2_rtos_handle;
extern uart_handle_t UART2_uart_handle;
extern uart_rtos_config_t UART2_rtos_config;
extern uart_rtos_handle_t UART4_rtos_handle;
extern uart_handle_t UART4_uart_handle;
extern uart_rtos_config_t UART4_rtos_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
